### PR TITLE
save: remove repoRootForImportPath

### LINKED ISSUE #25: "glock save" extremely slow on vanity import paths
I have a repo (git.encryptio.com/slime) which has many subpackage imports under vanity import paths. It takes nearly a minute to run `glock save git.encryptio.com/slime`. `glock` is sending remote requests for vanity URL metadata, yet the information used by `glock save` to generate its output is completely local (I've written a basic script to do this for me, it finishes in 0.3 seconds and generates bit-for-bit identical output.)

This seems to stem from a non-optimized use of vcs.go's `repoRootForImportPath`, which runs various remote verifications to ensure proper behavior for `go get` (which is completely irrelevant for `glock save`.)

### PR DESCRIPTION
**Pull request by tamird**
This greatly speeds up `glock save`. Closes #25.

Before:

$ time glock save github.com/cockroachdb/cockroach

real	0m59.388s
user	0m7.946s
sys	0m3.877s

After:

$ time glock save github.com/cockroachdb/cockroach

real	0m3.729s
user	0m7.353s
sys	0m3.442s

### CODE REVIEW

**Comment by tamird** [comment]
@robfig ping.

**Comment by robfig** [comment]
That seems quite desirable, but is there functionality that we lose with this change?

**Comment by tamird** [comment]
I didn't pour over the code - I simply went by your suggestion in #25.

**Comment by robfig** [comment]
Ah, forgot about that. As long as you've tested and everything's good.. Thanks!

**Pull request merged**
